<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.51.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClaudeTestApp.AI\ClaudeTestApp.AI.csproj" />
    <ProjectReference Include="..\ClaudeTestApp.Application\ClaudeTestApp.Application.csproj" />
    <ProjectReference Include="..\ClaudeTestApp.MCP\ClaudeTestApp.MCPServer.csproj" />
  </ItemGroup>

</Project>
